caicloud/aloe

.travis.yaml

**What this PR does**
**why we need it**

feat(ci): add travis ci config

---

examples/crud/server/server.go
framework.go
matcher/map.go
matcher/matcher.go
template/template.go

**What this PR does**
**why we need it**

style(linter): fix go report problems

---

.travis.yml

**What this PR does**
- skip test in examples
**why we need it**
examples will be rewritten without go-restful

chore(ci): skip examples

---

README.md

Fixes #
```release-note
add status badges
```

add status badges

---

OWNERS

Add OWNERS for caicloud-bot
Fixes #
/cc @liubog2008 @zjj2wry 
```release-note
NONE
```

chore(owners): add OWNERS file

---

examples/crud/README.md
examples/crud/crud.go

There is a race in the example setup.  ListenAndServe is a convenient method for Listen() and Serve().  Separating the two will make sure that after Serve(), our server is really ready to accept connection.
Fixes #
/cc @liubog2008 @zjj2wry 
```release-note
NONE
```

fix(example): make example really work

---

README.md

Update README to fix link and make it more readable.
/cc @liubog2008 @zjj2wry 
```release-note
NONE
```

docs(readme): fix and update readme

---

README.md
cleaner/cleaner.go
context.go
data/read.go
data/validation.go
examples/crud/crud.go
examples/crud/server/server.go
examples/crud/testdata/_context.yaml
examples/crud/testdata/create.yaml
examples/crud/testdata/nested/_context.yaml
examples/crud/testdata/nested/get.yaml
examples/crud/testdata/verify.yaml
framework.go
preset/preset.go
roundtrip/matcher.go
roundtrip/merge.go
template/template.go
template/template_test.go
types/context.go
types/doc.go
types/perset.go
utils/jsonutil/json.go
utils/jsonutil/variable.go

Fixes #
```release-note
NONE
```

feat(framework): add cleaner and presetter for context

---

.gometalinter.json
examples/crud/testdata/_context.yaml
framework.go
preset/header.go
roundtrip/matcher.go
roundtrip/merge.go
types/roundtrip.go

Fixes #
```release-note
NONE
```

feat(presetter): add default header presetter

---

.gometalinter.json

delete gas linter
Fixes #
Reference to #
/cc @ddysher 
```release-note
1. delete gas from linters
```

chore(linter): delete gas from linter

---

OWNERS

@liubog2008 
Fixes #
Reference to #
```release-note
NONE
```

add ddysher to approver

---

aloe.go
utils/glog/flag.go

Fixes #
Reference to #
```release-note
NONE
```

feat(flag): add prefix for glog

---

runtime/render.go
runtime/roundtrip.go

Fixes #
Reference to #
/cc @bbbmj 
```release-note
- add path template into roundtrip template
```

feat(preset): add path template for roundtrip template

---

aloe.go
framework/framework.go
roundtrip/http.go

Fixes #
Reference to #
/cc @bbbmj 
```release-note
1. add CustomizeClient function for framework
```

feat(framework): support custom client

---

data/validation.go
data/validation_test.go
examples/crud/testdata/context.yaml
examples/crud/testdata/delete.yaml
examples/crud/testdata/get.yaml
examples/crud/testdata/nested/context.yaml
examples/crud/testdata/nested/get.yaml
examples/crud/testdata/put.yaml
examples/crud/testdata/verify.yaml
framework/context.go
framework/framework.go
roundtrip/matcher.go
runtime/construct.go
runtime/context.go
runtime/render.go
runtime/roundtrip.go
template/select.go
types/context.go
types/roundtrip.go
types/var.go
utils/jsonutil/array.go
utils/jsonutil/helper.go
utils/jsonutil/json.go
utils/jsonutil/map.go
utils/jsonutil/variable.go

Fixes #
Reference to #
/cc @bbbmj 
```release-note
- Add exports in context -- only exported variables can be inherited
- Fix definition bug in loop -- when and loop can work fine together
- Clean code about validated flow
```

 feat(exports): add variable exports of context and fix def bug of loop

---

OWNERS

Fixes #
Reference to #
/cc @liubog2008 
```release-note
NONE
```

chore(*): add bbbmj to OWNERS

---

examples/crud/testdata/context.yaml
examples/crud/testdata/delete.yaml
examples/crud/testdata/get.yaml
examples/crud/testdata/put.yaml
framework/context.go
framework/framework.go
matcher/map.go
matcher/matcher.go
matcher/matcher_test.go
matcher/slice.go
matcher/sp.go
runtime/render.go
template/func.go
template/len.go
template/lexer.go
template/select.go
template/template.go
template/template_test.go
utils/jsonutil/array.go
utils/jsonutil/helper.go
utils/jsonutil/json.go
utils/jsonutil/map.go
utils/jsonutil/variable.go

Fixes #
Reference to #
/cc @bbbmj 
```release-note
- add $len and $match matcher
- fix selector bug -- use [n] to replace n to select elem from array
```

feat(matcher): add $match and $len matcher

---

utils/jsonutil/helper.go

Fixes #
Reference to #
/cc @bbbmj 
```release-note
NONE
```

fix(crash): fix conflict crash problem

---

framework/context.go

Fixes #
Reference to #
/cc @bbbmj 
```release-note
- add type conversion funcs for eval expression
```

feat(when): add type conversion funcs for eval expression

---

framework/framework.go
roundtrip/http.go
runtime/roundtrip.go
types/roundtrip.go

Fixes #
Reference to #
/cc @bbbmj @liwandaniel 
```release-note
- add multiple clients support
```

feat(multiclient): add support of multiple clients in roundtrip

---

runtime/render.go
types/roundtrip.go

Fixes #
Reference to #
/cc @bbbmj @liwandaniel 
```release-note
- fix missing client render
- add absolute api path support
- change host and scheme to support template
```

feat(roundtrip): support absolute api path and fix render client bug

---

runtime/render.go

Fixes #
Reference to #
```release-note
NONE
```

fix(render):headers set fail
